AllCops:
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment: 
  Enabled: false
    
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false 

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Layout/LineLength:
  Enabled: false
